--  PostgreSQL
\c aula03m
USE aula03m;

-- Clientes
CREATE TABLE clientes ( 
    id  INT GENERATED BY DEFAULT AS IDENTITY, 
    nome    VARCHAR(100), 
    email   VARCHAR(100), 
    PRIMARY KEY(id) 
);

-- Pedidos
CREATE TABLE pedidos ( 
    id  INT GENERATED BY DEFAULT AS IDENTITY, 
    cliente_id  INT, 
    valor   NUMERIC(10,2), 
    data_pedido DATE DEFAULT CURRENT_DATE, 
    PRIMARY KEY (id), 
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) 
);

-- Log pedidos
CREATE TABLE log_pedidos ( 
    id  INT GENERATED BY DEFAULT AS IDENTITY, 
    mensagem    TEXT, 
    data_log    TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY(id) 
);

-- Inserindo clientes
INSERT INTO clientes (nome, email) VALUES 
    ('João Silva', 'joao@email.com'), 
    ('Maria Souza', 'maria@email.com');

-- Inserindo pedidos
INSERT INTO pedidos (cliente_id, valor, data_pedido) VALUES 
    (1, 199.90, '2025-03-01'), 
    (1, 49.90, '2025-03-10'), 
    (2, 99.90, '2025-03-15');

-- TRIGGER AFTER INSERT
CREATE OR REPLACE FUNCTION log_pedido_insert() 
RETURNS TRIGGER AS $$ 
BEGIN INSERT 
    INTO log_pedidos (mensagem) 
    VALUES ('Novo pedido inserido para o cliente ID ' || NEW.cliente_id); 
    RETURN NEW; 
END; 
$$ LANGUAGE plpgsql; 

CREATE TRIGGER trg_pedidos_AI 
AFTER INSERT ON pedidos 
FOR EACH ROW 
EXECUTE FUNCTION log_pedido_insert();

-- TRIGGER BEFORE DELETE
CREATE OR REPLACE FUNCTION log_delete_cliente() 
RETURNS TRIGGER AS $$ 
BEGIN 
    INSERT INTO log_pedidos (mensagem) 
    VALUES ('Cliente ID ' || OLD.id || ' será removido: ' || OLD.nome); 
    RETURN OLD; 
END; 
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_clientes_BD 
BEFORE DELETE ON clientes 
FOR EACH ROW 
EXECUTE FUNCTION log_delete_cliente();

-- TRIGGER AFTER UPDATE
CREATE OR REPLACE FUNCTION log_update_pedido() 
RETURNS TRIGGER AS $$ 
BEGIN 
    INSERT INTO log_pedidos (mensagem) 
    VALUES ( 
        'Pedido ID ' || OLD.id || ' atualizado. Valor anterior: ' || OLD.valor || ', novo valor: ' || NEW.valor 
    ); 
    RETURN NEW; 
END; 
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pedidos_AU 
AFTER UPDATE ON pedidos 
FOR EACH ROW 
EXECUTE FUNCTION log_update_pedido();

-- PROCEDURE para inserir novo cliente
CREATE OR REPLACE PROCEDURE inserir_cliente( 
    IN nome_cli TEXT, 
    IN email_cli TEXT 
) 
LANGUAGE plpgsql 
AS $$ 
BEGIN 
    INSERT INTO clientes (nome, email) 
    VALUES (nome_cli, email_cli); 
END; 
$$;

    -- Chamando a procedure 
    CALL inserir_cliente('Carlos Mendes', 'carlos@email.com');

-- FUNÇÃO para verificar total de pedidos por cliente
CREATE OR REPLACE FUNCTION total_pedidos(id_cliente INT) 
RETURNS INT AS $$ 
DECLARE 
    total INT; 
BEGIN 
    SELECT COUNT(*) INTO total 
    FROM pedidos 
    WHERE cliente_id = id_cliente; 
    RETURN total; 
END; 
$$ LANGUAGE plpgsql;

    -- Chamando a função 
    SELECT total_pedidos(1);

-- FUNÇÃO com retorno de múltiplas colunas
-- Retorna nome, email e total de pedidos de um cliente
CREATE OR REPLACE FUNCTION dados_cliente(id_cliente INT) 
RETURNS TABLE(nome TEXT, email TEXT, total_pedidos INT) AS $$ 
BEGIN 
    RETURN QUERY 
    SELECT c.nome, c.email, COUNT(p.id) 
    FROM clientes c 
    LEFT JOIN pedidos p ON c.id = p.cliente_id 
    WHERE c.id = id_cliente 
    GROUP BY c.nome, c.email; 
END; 
$$ LANGUAGE plpgsql;

    -- Chamando a função 
    SELECT * FROM dados_cliente(1);

-- VIEW que retorna nome, email e total de pedidos por cliente
CREATE VIEW dados_cliente_view AS 
SELECT 
    c.id, 
    c.nome, 
    c.email, 
    COUNT(p.id) AS total_pedidos 
FROM 
    clientes c 
LEFT JOIN 
    pedidos p ON c.id = p.cliente_id 
GROUP BY 
    c.id, c.nome, c.email;

    -- Consultando a VIEW 
    SELECT * FROM dados_cliente_view WHERE id = 1;

-- Visão (VIEW) simples com JOIN
CREATE VIEW resumo_pedidos AS 
SELECT c.nome, COUNT(p.id) AS total_pedidos, SUM(p.valor) AS valor_total 
FROM clientes c 
LEFT JOIN pedidos p ON c.id = p.cliente_id 
GROUP BY c.nome;

    -- Consultando a visão 
    SELECT * FROM resumo_pedidos;

